spring:
  application:
    name: medron

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/medron

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true